version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./wordpress:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wordpress_net

  db:
    image: mysql:8.0   # ✅ ARM-compatible version
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress   # ✅ Create the 'wordpress' DB
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net

volumes:
  db_data:

networks:
  wordpress_net:
    driver: bridge
